### ISSUE TITLE
Documentation for the library that enables developers to read and write Java class files and bytecode

### ISSUE THREAD

**Issue by mrckhff** [ingokegel/jclasslib#14]
Hello Ingo, thank you so much for this great software!!!

Is there a documentation on how to use the library that enables developers to read and write Java class files and bytecode?

Thanks in advance.

**Comment by ingokegel** [comment]
Thanks for your positive feedback.

Actually, the main purpose is the bytecode viewer, not reading and writing bytecode. Today there are many options for reading and modifying bytecode. When I wrote the viewer back in 2002 the situation was quite different. Apart from the KDoc on the classes in the data module I don't plan to supply any documentation.
