### ISSUE TITLE
IDEA plugin doesn't handle class files opened directly

### ISSUE THREAD

**Issue by Zastai** [ingokegel/jclasslib#18]
IDEA supports opening .class files directly (and decompiles them using Fernflower).
The built-in bytecode viewer has no problem viewing the bytecode for such files.

However, attempting to view them using the jclasslib plugin results in an error dialog: "Class file could not be found: <top level class>".
It would be really nice to be able to view those using jclasslib from within the IDE.

My use case is class files generated by a build task - they are not part of the project, nor do they have a corresponding source file in the project.

**Comment by huanjinzi** [comment]
i met the same problem too .how to fix it?

**Comment by Zastai** [comment]
I just worked around it by installing the standalone jclasslib and using it to open .class files from explorer when neded.
But it would indeed be nice if the plugin could handle this.

**Comment by crimsonlock** [comment]
The solution is : focused on JAVA FILE NOT CLASS FILE when you start jclasslib, it works well in IDEA.

**Comment by Zastai** [comment]
Please read the ticket. My use case is for class files that generated in code (via the ASM library), and have no corresponding java source file in the project. And I invoke jclasslib from the fake/decompiled source idea produces.

**Comment by ingokegel** [comment]
Fixed by f613c86a997245dc24c6544ac78e077e20cc6496
