### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by FlorianLoch** [ingokegel/jclasslib#19]
I am experiencing the following error directly at the startup:
![image](https://user-images.githubusercontent.com/5587805/32325430-3c5d58cc-bfcf-11e7-9677-875d5cdcbc6f.png)

I am using Oracle's JDK in version 1.8.0_111 on macOS 10.13.

Clicking "OK" results in closing jclasslib, just leaving the window open works fine but doesn't look nice :)

**Comment by ingokegel** [comment]
This is the same as #15. I've just published 5.2.1 to fix this.

**Comment by FlorianLoch** [comment]
Sorry, just looked at the open issues... my bad

**Comment by ingokegel** [comment]
In any case, thanks for reminding me to release this important fix :-)
