### ISSUE TITLE
allow selecting method signatures and names for copying

### ISSUE THREAD

**Issue by pdeva** [ingokegel/jclasslib#2]
it seems its not current possible to copy method signatures from the ui.
please allow selecting text in the following panel so method signatures can be copied.

![2015-01-25_1506](https://cloud.githubusercontent.com/assets/3190176/5893733/f4bc0df4-a4a3-11e4-9d72-d15353b5a5a1.png)

**Comment by ingokegel** [comment]
Good idea, until now only the container nodes had a copy to clipboard action. Now the methods and fields have one too and CTRL-C works in the tree.
