### ISSUE TITLE
what about kotlin？

### ISSUE THREAD

**Issue by lovingning** [ingokegel/jclasslib#25]
![_20180510122522](https://user-images.githubusercontent.com/17874282/39852187-b8852f3e-544d-11e8-8e9d-6b03e9c71a5b.png)

WTF？

**Comment by ingokegel** [comment]
Finding a class file from a selected element is actually quite complicated, please see

https://github.com/ingokegel/jclasslib/blob/master/modules/idea/src/main/kotlin/org/gjt/jclasslib/idea/ClassFileLocation.kt

Please feel free to debug the situation in your case and find out what goes wrong. There is an "IDEA" run configuration in the jclasslib project that you can start in debug mode and set breakpoints in that source file.

**Comment by ingokegel** [comment]
Fixed by f613c86a997245dc24c6544ac78e077e20cc6496
