### ISSUE TITLE
Allow editing

### ISSUE THREAD

**Issue by Vampire** [ingokegel/jclasslib#26]
It would be really awesome if jclasslib (actually the IJ plugin in my case) would allow editing of bytecode and then saving as class file like CafeBabe used to support.

**Comment by Vampire** [comment]
My use-case is that I want to edit everything. :grinning:
I remember e. g. fixing an IJ plugin with CafeBabe that was not working anymore in a new version.
I don't remember though which it was as it was years ago.

Another concrete use case would be to replace `if (licensed)` by `if (true)`. :grin:  Of course just as exercise, if at all. :smiley:

**Comment by lovedebug** [comment]
So, I hope i could edit the class file.
Thanks for your nice work.

**Comment by fablocke** [comment]
Need this feature as well :/
Also for editing the class file

**Comment by ingokegel** [comment]
It's here!
