### ISSUE TITLE
the newest IntelJ IDEA doesn't support the plugin

### ISSUE THREAD

**Issue by chenyurong** [ingokegel/jclasslib#27]
I found the plugin of jclasslib in JetBrain Plugin website.

https://plugins.jetbrains.com/plugin/9248-jclasslib-bytecode-viewer

but when I download the latest plugin, and install from disk, the IntelJ IDEA tell me that it doesn't support this plugin.

![image](https://user-images.githubusercontent.com/9125445/45694764-8ec9a880-bb92-11e8-836f-759cdc5aa18d.png)

hope you can fix it ASAP, thanks for ur contribution.

**Comment by ingokegel** [comment]
Works for me with 2018.2.3.

**Comment by chouchouyu** [comment]
The plugin dosen't work for my IntelJ IDEA too.

![IDE](https://raw.githubusercontent.com/chouchouyu/translate/master/others/IDE.png)
![plugin](https://raw.githubusercontent.com/chouchouyu/translate/master/others/plugin.png)
![view](https://raw.githubusercontent.com/chouchouyu/translate/master/others/view.png)

**Comment by ingokegel** [comment]
Fixed in 5.3.1
