### ISSUE TITLE
some bytecode instruction weblink not exist

### ISSUE THREAD

**Issue by e45240** [ingokegel/jclasslib#29]
![image](https://user-images.githubusercontent.com/19710910/54687241-139f7a00-4b56-11e9-9400-908ee8c331c7.png)
![image](https://user-images.githubusercontent.com/19710910/54687247-17330100-4b56-11e9-993f-65ef861842d0.png)
![image](https://user-images.githubusercontent.com/19710910/54687294-33cf3900-4b56-11e9-895e-df57a9bfeb39.png)

……

**Comment by ingokegel** [comment]
Works for me, must have been a temporary problem with the server
