### ISSUE TITLE
current version doesnt have latest features

### ISSUE THREAD

**Issue by pdeva** [ingokegel/jclasslib#3]
could you please release the latest version which supports copying of method signatures.

**Comment by ingokegel** [comment]
It's not really enough for a release yet. You can build the JAR files yourself by executing 

    gradlew jar

in the root directory (no gradle installation required).

Afterwards, the JAR file can be found in build/gradle/browser/libs/jclasslib-browser.jar

Just overwrite the same file in your jclasslib installation.
