### ISSUE TITLE
how to set the bytecode font size becasue of the bytecode in my android studio is too small to read

### ISSUE THREAD

**Issue by aLLLiyyy** [ingokegel/jclasslib#34]

**Comment by ingokegel** [comment]
Please post a screenshot

**Comment by aLLLiyyy** [comment]
my condition is like the picture bellow, i appreciate you can help me figure out this problems,








![QQ截图20191007232646](https://user-images.githubusercontent.com/36837316/66326040-e7fda900-e95a-11e9-8cdd-ef616e14e801.png)

**Comment by ingokegel** [comment]
The bytecode display now uses the configured editor font. You can build the plugin yourself with

    ./gradlew buildPlugin

the plugin JAR is created in `build/gradle/idea/distributions`.
