### ISSUE TITLE
Silent install does not work

### ISSUE THREAD

**Issue by tim-lebedkov** [ingokegel/jclasslib#35]
I created a package for JClassLib: https://www.npackd.org/p/jclasslib64 , but the silent installation options does not work:

`"%setup%" -q -dir "%CD%" && del /f /q "%setup%"`

The installer just shows a dialog
![screen5](https://user-images.githubusercontent.com/831371/77820008-6b64af80-70df-11ea-8dd5-865933a2d09d.png)

**Comment by ingokegel** [comment]
Thanks for the report, this will be fixed in the next release.
