### ISSUE TITLE
Click reload, close... nothing happens

### ISSUE THREAD

**Issue by vvVenom** [ingokegel/jclasslib#37]
I click the button on the toolbar does not work, I ca n’t even close it
![image](https://user-images.githubusercontent.com/58068445/80297529-636b5e80-87b6-11ea-86ef-c2788ffe42d3.png)

Intellij plugin 5.4

**Comment by ingokegel** [comment]
I cannot reproduce with 2019.2 or 2020.1. The close button works for me. Does the close button the the tab work for you?

**Comment by vvVenom** [comment]
yes, only the tab close button work for me

**Comment by ingokegel** [comment]
Anything in the IDEA log file? What version do you use?

**Comment by vvVenom** [comment]
> Anything in the IDEA log file? What version do you use?

i used `Android Studio 4.0 beta05`
![image](https://user-images.githubusercontent.com/58068445/80301118-c66bee00-87d4-11ea-94a8-d61949d28297.png)

**Comment by ingokegel** [comment]
OK, I don't have Android Studio, but I don't see why the close button should not work, is there an exception in the exception manager or in the log file?

**Comment by vvVenom** [comment]
> OK, I don't have Android Studio, but I don't see why the close button should not work, is there an exception in the exception manager or in the log file?

OH...I think I do n’t know, where can I get them?

**Comment by ingokegel** [comment]
Please see https://stackoverflow.com/questions/19784877/how-to-find-the-logs-on-android-studio

**Comment by vvVenom** [comment]
I have switched from `android studio` to `intellij idea`, so this issue can be closed, thanks!
