### ISSUE TITLE
Font size in `bytecode` tab is too small

### ISSUE THREAD

**Issue by kamil09875** [ingokegel/jclasslib#4]
![screenshot_2](https://cloud.githubusercontent.com/assets/1507072/8619202/272bf56c-2715-11e5-9a44-63620a92acd7.png)

As above, font size is so small that text is not readable (on screen with high pixel density such as mine). Maybe change default font size or add an option to adjust it yourself?

**Comment by ingokegel** [comment]
Can you add             

    System.err.println("baseFont.getSize() = " + baseFont.getSize());
    System.err.println("new JTextArea().getSize() = " + new JTextArea().getFont().getSize());

after ByteCodeDisplay:69 and send me the output?

**Comment by kamil09875** [comment]
Sure:

```
baseFont.getSize() = 9
new JTextArea().getSize() = 9
```

**Comment by ingokegel** [comment]
I don't have a Windows HiDPI system at the moment. I will get one soon and then I will fix it.

**Comment by gschukin** [comment]
I'm facing same issue on non HiDPI system.

**Comment by ingokegel** [comment]
Bytecode display now uses a JTextPane instead of a custom component that draws TextLayouts

**Comment by gschukin** [comment]
On master I'm still facing this issue
![image](https://cloud.githubusercontent.com/assets/1642745/15318793/71e9855e-1c30-11e6-9417-bf828902f6a1.png)

**Comment by ingokegel** [comment]
Thank you, the screen shot was helpful. Please try again with the latest commit.

**Comment by gschukin** [comment]
Much better. There is still a little issue with line numbers on the left. But main display is fine
![image](https://cloud.githubusercontent.com/assets/1642745/15319632/7e7accb6-1c34-11e6-9fbc-5282c782706f.png)

Thank you

**Comment by ingokegel** [comment]
Thank you. The line numbers are intentionally smaller.
