### ISSUE TITLE
Warning needed when overwriting a file 

### ISSUE THREAD

**Issue by platypusguy** [ingokegel/jclasslib#68]
Your "save modified class files" function simply overwrites the existing file(s). IMHO it should definitely ask the user whether they want to overwrite the existing file(s) or save the modified file(s) to a different location.

**Comment by ingokegel** [comment]
Thanks for your feedback. You're right, I've implemented this for the next version

**Comment by platypusguy** [comment]
Thanks a lot. We're beginning a cycle of testing for Jacobin JVM in which we expect to rely on jclasslib a lot, so having this safety feature is very welcome. Thanks for hearing and acting on this concern!
